# Project
version=0.1.21
group=com.koomplo.wizardry
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Electroblob's Wizardry Redux
mod_id=ebwizardry
mod_author=Binaris
license=MIT
description=Explore and discover an intuitive and big magic system. Recreation of the old RPG classic mod. Unofficial NeoForge 1.21.1 port.

# NeoForge
neo_version=21.1.235

# ParchmentMC
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies (versões resolvidas no Step 1)
curios_version=9.5.1+1.21.1
cloth_config_version=15.0.140
jei_version=19.27.0.346

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
