package com.binaris.wizardry.datagen.provider;

import com.binaris.wizardry.WizardryMainMod;
import com.binaris.wizardry.api.content.event.EBDiscoverSpellEvent;
import com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger;
import com.binaris.wizardry.setup.registries.*;
import net.minecraft.advancements.Advancement;
import net.minecraft.advancements.AdvancementRewards;
import net.minecraft.advancements.FrameType;
import net.minecraft.advancements.RequirementsStrategy;
import net.minecraft.advancements.critereon.*;
import net.minecraft.core.HolderLookup;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.common.data.ForgeAdvancementProvider;
import org.jetbrains.annotations.NotNull;

import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.function.Consumer;

@SuppressWarnings("unused")
public class EBAdvancementsProvider implements ForgeAdvancementProvider.AdvancementGenerator {

    private static final List<Item> WARLOCK_ITEMS = List.of(EBItems.WIZARD_HAT.get(), EBItems.WIZARD_ROBE.get(), EBItems.WIZARD_LEGGINGS.get(), EBItems.WIZARD_BOOTS.get(), (EBItems.WIZARD_HAT_EARTH.get()), EBItems.WIZARD_ROBE_EARTH.get(), EBItems.WIZARD_LEGGINGS_EARTH.get(), EBItems.WIZARD_BOOTS_EARTH.get(), (EBItems.WIZARD_HAT_FIRE.get()), EBItems.WIZARD_ROBE_FIRE.get(), EBItems.WIZARD_LEGGINGS_FIRE.get(), EBItems.WIZARD_BOOTS_FIRE.get(), (EBItems.WIZARD_HAT_HEALING.get()), EBItems.WIZARD_ROBE_HEALING.get(), EBItems.WIZARD_LEGGINGS_HEALING.get(), EBItems.WIZARD_BOOTS_HEALING.get(), (EBItems.WIZARD_HAT_ICE.get()), EBItems.WIZARD_ROBE_ICE.get(), EBItems.WIZARD_LEGGINGS_ICE.get(), EBItems.WIZARD_BOOTS_ICE.get(), (EBItems.WIZARD_HAT_LIGHTNING.get()), EBItems.WIZARD_ROBE_LIGHTNING.get(), EBItems.WIZARD_LEGGINGS_LIGHTNING.get(), EBItems.WIZARD_BOOTS_LIGHTNING.get(), (EBItems.WIZARD_HAT_NECROMANCY.get()), EBItems.WIZARD_ROBE_NECROMANCY.get(), EBItems.WIZARD_LEGGINGS_NECROMANCY.get(), EBItems.WIZARD_BOOTS_NECROMANCY.get(), (EBItems.WIZARD_HAT_SORCERY.get()), EBItems.WIZARD_ROBE_SORCERY.get(), EBItems.WIZARD_LEGGINGS_SORCERY.get(), EBItems.WIZARD_BOOTS_SORCERY.get());
    private static final List<Item> SAGE_ITEMS = List.of(EBItems.SAGE_HAT.get(), EBItems.SAGE_ROBE.get(), EBItems.SAGE_LEGGINGS.get(), EBItems.SAGE_BOOTS.get(), EBItems.SAGE_HAT_EARTH.get(), EBItems.SAGE_ROBE_EARTH.get(), EBItems.SAGE_LEGGINGS_EARTH.get(), EBItems.SAGE_BOOTS_EARTH.get(), EBItems.SAGE_HAT_FIRE.get(), EBItems.SAGE_ROBE_FIRE.get(), EBItems.SAGE_LEGGINGS_FIRE.get(), EBItems.SAGE_BOOTS_FIRE.get(), EBItems.SAGE_HAT_HEALING.get(), EBItems.SAGE_ROBE_HEALING.get(), EBItems.SAGE_LEGGINGS_HEALING.get(), EBItems.SAGE_BOOTS_HEALING.get(), EBItems.SAGE_HAT_ICE.get(), EBItems.SAGE_ROBE_ICE.get(), EBItems.SAGE_LEGGINGS_ICE.get(), EBItems.SAGE_BOOTS_ICE.get(), EBItems.SAGE_HAT_LIGHTNING.get(), EBItems.SAGE_ROBE_LIGHTNING.get(), EBItems.SAGE_LEGGINGS_LIGHTNING.get(), EBItems.SAGE_BOOTS_LIGHTNING.get(), EBItems.SAGE_HAT_NECROMANCY.get(), EBItems.SAGE_ROBE_NECROMANCY.get(), EBItems.SAGE_LEGGINGS_NECROMANCY.get(), EBItems.SAGE_BOOTS_NECROMANCY.get(), EBItems.SAGE_HAT_SORCERY.get(), EBItems.SAGE_ROBE_SORCERY.get(), EBItems.SAGE_LEGGINGS_SORCERY.get(), EBItems.SAGE_BOOTS_SORCERY.get());
    private static final List<Item> BATTLEMAGE_ITEMS = List.of(EBItems.BATTLEMAGE_HELMET.get(), EBItems.BATTLEMAGE_CHESTPLATE.get(), EBItems.BATTLEMAGE_LEGGINGS.get(), EBItems.BATTLEMAGE_BOOTS.get(), EBItems.BATTLEMAGE_HELMET_EARTH.get(), EBItems.BATTLEMAGE_CHESTPLATE_EARTH.get(), EBItems.BATTLEMAGE_LEGGINGS_EARTH.get(), EBItems.BATTLEMAGE_BOOTS_EARTH.get(), EBItems.BATTLEMAGE_HELMET_FIRE.get(), EBItems.BATTLEMAGE_CHESTPLATE_FIRE.get(), EBItems.BATTLEMAGE_LEGGINGS_FIRE.get(), EBItems.BATTLEMAGE_BOOTS_FIRE.get(), EBItems.BATTLEMAGE_HELMET_HEALING.get(), EBItems.BATTLEMAGE_CHESTPLATE_HEALING.get(), EBItems.BATTLEMAGE_LEGGINGS_HEALING.get(), EBItems.BATTLEMAGE_BOOTS_HEALING.get(), EBItems.BATTLEMAGE_HELMET_ICE.get(), EBItems.BATTLEMAGE_CHESTPLATE_ICE.get(), EBItems.BATTLEMAGE_LEGGINGS_ICE.get(), EBItems.BATTLEMAGE_BOOTS_ICE.get(), EBItems.BATTLEMAGE_HELMET_LIGHTNING.get(), EBItems.BATTLEMAGE_CHESTPLATE_LIGHTNING.get(), EBItems.BATTLEMAGE_LEGGINGS_LIGHTNING.get(), EBItems.BATTLEMAGE_BOOTS_LIGHTNING.get(), EBItems.BATTLEMAGE_HELMET_NECROMANCY.get(), EBItems.BATTLEMAGE_CHESTPLATE_NECROMANCY.get(), EBItems.BATTLEMAGE_LEGGINGS_NECROMANCY.get(), EBItems.BATTLEMAGE_BOOTS_NECROMANCY.get(), EBItems.BATTLEMAGE_HELMET_SORCERY.get(), EBItems.BATTLEMAGE_CHESTPLATE_SORCERY.get(), EBItems.BATTLEMAGE_LEGGINGS_SORCERY.get(), EBItems.BATTLEMAGE_BOOTS_SORCERY.get());
    private static final List<Item> WIZARD_ITEMS = List.of(EBItems.WIZARD_HAT.get(), EBItems.WIZARD_ROBE.get(), EBItems.WIZARD_LEGGINGS.get(), EBItems.WIZARD_BOOTS.get(), EBItems.WIZARD_HAT_EARTH.get(), EBItems.WIZARD_ROBE_EARTH.get(), EBItems.WIZARD_LEGGINGS_EARTH.get(), EBItems.WIZARD_BOOTS_EARTH.get(), EBItems.WIZARD_HAT_FIRE.get(), EBItems.WIZARD_ROBE_FIRE.get(), EBItems.WIZARD_LEGGINGS_FIRE.get(), EBItems.WIZARD_BOOTS_FIRE.get(), EBItems.WIZARD_HAT_HEALING.get(), EBItems.WIZARD_ROBE_HEALING.get(), EBItems.WIZARD_LEGGINGS_HEALING.get(), EBItems.WIZARD_BOOTS_HEALING.get(), EBItems.WIZARD_HAT_ICE.get(), EBItems.WIZARD_ROBE_ICE.get(), EBItems.WIZARD_LEGGINGS_ICE.get(), EBItems.WIZARD_BOOTS_ICE.get(), EBItems.WIZARD_HAT_LIGHTNING.get(), EBItems.WIZARD_ROBE_LIGHTNING.get(), EBItems.WIZARD_LEGGINGS_LIGHTNING.get(), EBItems.WIZARD_BOOTS_LIGHTNING.get(), EBItems.WIZARD_HAT_NECROMANCY.get(), EBItems.WIZARD_ROBE_NECROMANCY.get(), EBItems.WIZARD_LEGGINGS_NECROMANCY.get(), EBItems.WIZARD_BOOTS_NECROMANCY.get(), EBItems.WIZARD_HAT_SORCERY.get(), EBItems.WIZARD_ROBE_SORCERY.get(), EBItems.WIZARD_LEGGINGS_SORCERY.get(), EBItems.WIZARD_BOOTS_SORCERY.get());

    private static Advancement buildArmor(String location, ResourceLocation containerID, Advancement parent, Item display, Component name, Component desc, Collection<Item> items, Consumer<Advancement> consumer, ExistingFileHelper existingFileHelper) {
        Advancement.Builder builder = Advancement.Builder.advancement().parent(parent).display(display, name, desc, null, FrameType.GOAL, true, true, false).rewards(AdvancementRewards.EMPTY);

        for (Item item : items) {
            String itemName = item.getDefaultInstance().getItem().toString().replace("ebwizardry:", "");
            builder.addCriterion(itemName, new com.binaris.wizardry.content.advancement.WizardryContainerTrigger.TriggerInstance(containerID, ItemPredicate.Builder.item().of(item).build()));
        }

        builder.requirements(RequirementsStrategy.AND);
        return builder.save(consumer, WizardryMainMod.location(location), existingFileHelper);
    }

    @Override
    public void generate(HolderLookup.@NotNull Provider provider, @NotNull Consumer<Advancement> consumer, @NotNull ExistingFileHelper existingFileHelper) {
        Advancement root = Advancement.Builder.advancement().display(Items.BOOK, Component.translatable("advancement.ebwizardry.root"), Component.translatable("advancement.ebwizardry.root.desc"), WizardryMainMod.location("textures/gui/advancement_background.png"), FrameType.TASK, false, // show_toast
                false, // announce_to_chat
                false // hidden
        ).addCriterion("criteria", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MAGIC_CRYSTAL.get())).save(consumer, WizardryMainMod.location("root"), existingFileHelper);

        Advancement crystal = Advancement.Builder.advancement().parent(root).display(EBItems.MAGIC_CRYSTAL.get(), Component.translatable("advancement.ebwizardry.crystal"), Component.translatable("advancement.ebwizardry.crystal.desc"), null, FrameType.TASK, true, true, false).addCriterion("criteria", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MAGIC_CRYSTAL.get())).save(consumer, WizardryMainMod.location("crystal"), existingFileHelper);
        Advancement arcaneInit = Advancement.Builder.advancement().parent(crystal).display(EBItems.NOVICE_WAND.get(), Component.translatable("advancement.ebwizardry.arcane_initiate"), Component.translatable("advancement.ebwizardry.arcane_initiate.desc"), null, FrameType.TASK, true, true, false).addCriterion("criteria", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.NOVICE_WAND.get())).save(consumer, WizardryMainMod.location("arcane_initiate"), existingFileHelper);
        Advancement discoverSpell = Advancement.Builder.advancement().parent(arcaneInit).display(Items.PAPER, Component.translatable("advancement.ebwizardry.discover_spell"), Component.translatable("advancement.ebwizardry.discover_spell.desc"), null, FrameType.TASK, true, true, false).addCriterion("criteria", com.binaris.wizardry.content.advancement.SpellDiscoveryTrigger.TriggerInstance.discoverSpell(EBDiscoverSpellEvent.Source.CASTING)).save(consumer, WizardryMainMod.location("discover_spell"), existingFileHelper);
        Advancement wizardTower = Advancement.Builder.advancement().parent(arcaneInit).display(Items.BOOKSHELF, Component.translatable("advancement.ebwizardry.wizard_tower"), Component.translatable("advancement.ebwizardry.wizard_tower.desc"), null, FrameType.TASK, true, true, false).addCriterion("wizard_tower", PlayerTrigger.TriggerInstance.located(LocationPredicate.inStructure(EBWorldGen.WIZARD_TOWER))).save(consumer, WizardryMainMod.location("wizard_tower"), existingFileHelper);
        Advancement wizardTrade = Advancement.Builder.advancement().parent(wizardTower).display(Items.EMERALD, Component.translatable("advancement.ebwizardry.wizard_trade"), Component.translatable("advancement.ebwizardry.wizard_trade.desc"), null, FrameType.TASK, true, true, false).addCriterion("criteria", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.WIZARD_TRADE.getId())).save(consumer, WizardryMainMod.location("wizard_trade"), existingFileHelper);
        Advancement defeatEvilWizard = Advancement.Builder.advancement().parent(arcaneInit).display(EBItems.WIZARD_BOOTS_NECROMANCY.get(), Component.translatable("advancement.ebwizardry.defeat_evil_wizard"), Component.translatable("advancement.ebwizardry.defeat_evil_wizard.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", KilledTrigger.TriggerInstance.playerKilledEntity(EntityPredicate.Builder.entity().of(EBEntities.EVIL_WIZARD.get()))).save(consumer, WizardryMainMod.location("defeat_evil_wizard"), existingFileHelper);
        Advancement visitShrine = Advancement.Builder.advancement().parent(defeatEvilWizard).display(EBBlocks.EARTH_RUNESTONE.get(), Component.translatable("advancement.ebwizardry.visit_shrine"), Component.translatable("advancement.ebwizardry.visit_shrine.desc"), null, FrameType.TASK, true, true, false).addCriterion("shrine", PlayerTrigger.TriggerInstance.located(LocationPredicate.inStructure(EBWorldGen.SHRINE))).save(consumer, WizardryMainMod.location("visit_shrine"), existingFileHelper);
        Advancement spellFailure = Advancement.Builder.advancement().parent(discoverSpell).display(Items.PUMPKIN, Component.translatable("advancement.ebwizardry.spell_failure"), Component.translatable("advancement.ebwizardry.spell_failure.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.SPELL_FAILURE.getId())).save(consumer, WizardryMainMod.location("spell_failure"), existingFileHelper);
        Advancement identifySpell = Advancement.Builder.advancement().parent(discoverSpell).display(EBItems.IDENTIFICATION_SCROLL.get(), Component.translatable("advancement.ebwizardry.identify_spell"), Component.translatable("advancement.ebwizardry.identify_spell.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", com.binaris.wizardry.content.advancement.SpellDiscoveryTrigger.TriggerInstance.discoverSpell(EBDiscoverSpellEvent.Source.IDENTIFICATION_SCROLL)).save(consumer, WizardryMainMod.location("identify_spell"), existingFileHelper);
        Advancement enchantScroll = Advancement.Builder.advancement().parent(arcaneInit).display(EBItems.SCROLL.get(), Component.translatable("advancement.ebwizardry.enchant_scroll"), Component.translatable("advancement.ebwizardry.enchant_scroll.desc"), null, FrameType.TASK, true, true, false).addCriterion("enchant_scroll", new com.binaris.wizardry.content.advancement.WizardryContainerTrigger.TriggerInstance(EBAdvancementTriggers.ARCANE_WORKBENCH.getId(), ItemPredicate.Builder.item().of(EBItems.SCROLL.get()).build())).save(consumer, WizardryMainMod.location("enchant_scroll"), existingFileHelper);
        Advancement defeatRemnant = Advancement.Builder.advancement().parent(arcaneInit).display(EBItems.SPECTRAL_DUST_SORCERY.get(), Component.translatable("advancement.ebwizardry.defeat_remnant"), Component.translatable("advancement.ebwizardry.defeat_remnant.desc"), null, FrameType.TASK, true, true, false).addCriterion("fire", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_FIRE.get())).addCriterion("ice", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_ICE.get())).addCriterion("lightning", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_LIGHTNING.get())).addCriterion("necromancy", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_NECROMANCY.get())).addCriterion("earth", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_EARTH.get())).addCriterion("sorcery", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_SORCERY.get())).addCriterion("healing", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.SPECTRAL_DUST_HEALING.get())).save(consumer, WizardryMainMod.location("defeat_remnant"), existingFileHelper);
        Advancement findLibraryRuins = Advancement.Builder.advancement().parent(defeatRemnant).display(EBBlocks.SPRUCE_BOOKSHELF.get(), Component.translatable("advancement.ebwizardry.find_library_ruins"), Component.translatable("advancement.ebwizardry.find_library_ruins.desc"), null, FrameType.TASK, true, true, false).addCriterion("surface", PlayerTrigger.TriggerInstance.located(LocationPredicate.inStructure(EBWorldGen.LIBRARY_RUINS))).addCriterion("underground", PlayerTrigger.TriggerInstance.located(LocationPredicate.inStructure(EBWorldGen.UNDERGROUND_LIBRARY_RUINS))).save(consumer, WizardryMainMod.location("find_library_ruins"), existingFileHelper);
        Advancement buyMasterSpell = Advancement.Builder.advancement().parent(wizardTrade).display(EBItems.ASTRAL_DIAMOND.get(), Component.translatable("advancement.ebwizardry.buy_master_spell"), Component.translatable("advancement.ebwizardry.buy_master_spell.desc"), null, FrameType.GOAL, true, true, false).addCriterion("buy_master_spell", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.BUY_MASTER_SPELL.getId())).save(consumer, WizardryMainMod.location("buy_master_spell"), existingFileHelper);
        Advancement armorSet = Advancement.Builder.advancement().parent(arcaneInit).display(EBItems.WIZARD_HAT.get(), Component.translatable("advancement.ebwizardry.armor_set"), Component.translatable("advancement.ebwizardry.armor_set.desc"), null, FrameType.TASK, true, true, false).addCriterion("wizard_set", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.WIZARD_HAT.get(), EBItems.WIZARD_ROBE.get(), EBItems.WIZARD_LEGGINGS.get(), EBItems.WIZARD_BOOTS.get())).save(consumer, WizardryMainMod.location("armor_set"), existingFileHelper);
        Advancement apprentice = Advancement.Builder.advancement().parent(arcaneInit).display(EBItems.APPRENTICE_WAND.get(), Component.translatable("advancement.ebwizardry.apprentice"), Component.translatable("advancement.ebwizardry.apprentice.desc"), null, FrameType.TASK, true, true, false).addCriterion("magic", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_WAND.get())).addCriterion("fire", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_FIRE_WAND.get())).addCriterion("ice", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_ICE_WAND.get())).addCriterion("lightning", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_LIGHTNING_WAND.get())).addCriterion("necromancy", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_NECROMANCY_WAND.get())).addCriterion("earth", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_EARTH_WAND.get())).addCriterion("sorcery", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_SORCERY_WAND.get())).addCriterion("healing", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.APPRENTICE_HEALING_WAND.get())).save(consumer, WizardryMainMod.location("apprentice"), existingFileHelper);
        Advancement specialUpgrade = Advancement.Builder.advancement().parent(apprentice).display(EBItems.CONDENSER_UPGRADE.get(), Component.translatable("advancement.ebwizardry.special_upgrade"), Component.translatable("advancement.ebwizardry.special_upgrade.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.SPECIAL_UPGRADE.getId())).save(consumer, WizardryMainMod.location("special_upgrade"), existingFileHelper);
        Advancement angerWizard = Advancement.Builder.advancement().parent(wizardTrade).display(Items.IRON_SWORD, Component.translatable("advancement.ebwizardry.anger_wizard"), Component.translatable("advancement.ebwizardry.anger_wizard.desc"), null, FrameType.TASK, true, true, false).addCriterion("anger_wizard", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.ANGER_WIZARD.getId())).save(consumer, WizardryMainMod.location("anger_wizard"), existingFileHelper);
        Advancement advanced = Advancement.Builder.advancement().parent(apprentice).display(EBItems.ADVANCED_WAND.get(), Component.translatable("advancement.ebwizardry.advanced"), Component.translatable("advancement.ebwizardry.advanced.desc"), null, FrameType.TASK, true, true, false).addCriterion("magic", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_WAND.get())).addCriterion("fire", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_FIRE_WAND.get())).addCriterion("ice", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_ICE_WAND.get())).addCriterion("lightning", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_LIGHTNING_WAND.get())).addCriterion("necromancy", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_NECROMANCY_WAND.get())).addCriterion("earth", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_EARTH_WAND.get())).addCriterion("sorcery", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_SORCERY_WAND.get())).addCriterion("healing", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.ADVANCED_HEALING_WAND.get())).save(consumer, WizardryMainMod.location("advanced"), existingFileHelper);
        Advancement craftLectern = Advancement.Builder.advancement().parent(findLibraryRuins).display(EBBlocks.SPRUCE_LECTERN.get(), Component.translatable("advancement.ebwizardry.craft_lectern"), Component.translatable("advancement.ebwizardry.craft_lectern.desc"), null, FrameType.TASK, true, true, false).addCriterion("oak", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.OAK_LECTERN.get())).addCriterion("spruce", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.SPRUCE_LECTERN.get())).addCriterion("birch", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.BIRCH_LECTERN.get())).addCriterion("jungle", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.JUNGLE_LECTERN.get())).addCriterion("acacia", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.ACACIA_LECTERN.get())).addCriterion("dark_oak", InventoryChangeTrigger.TriggerInstance.hasItems(EBBlocks.DARK_OAK_LECTERN.get())).save(consumer, WizardryMainMod.location("craft_lectern"), existingFileHelper);
        Advancement master = Advancement.Builder.advancement().parent(advanced).display(EBItems.MASTER_WAND.get(), Component.translatable("advancement.ebwizardry.master"), Component.translatable("advancement.ebwizardry.master.desc"), null, FrameType.GOAL, true, true, false).addCriterion("magic", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_WAND.get())).addCriterion("fire", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_FIRE_WAND.get())).addCriterion("ice", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_ICE_WAND.get())).addCriterion("lightning", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_LIGHTNING_WAND.get())).addCriterion("necromancy", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_NECROMANCY_WAND.get())).addCriterion("earth", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_EARTH_WAND.get())).addCriterion("sorcery", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_SORCERY_WAND.get())).addCriterion("healing", InventoryChangeTrigger.TriggerInstance.hasItems(EBItems.MASTER_HEALING_WAND.get())).save(consumer, WizardryMainMod.location("master"), existingFileHelper);
        Advancement warlock = buildArmor("warlock", EBAdvancementTriggers.ARCANE_WORKBENCH.getId(), armorSet, EBItems.WARLOCK_HOOD.get(), Component.translatable("advancement.ebwizardry.warlock"), Component.translatable("advancement.ebwizardry.warlock.desc"), WARLOCK_ITEMS, consumer, existingFileHelper);
        Advancement sage = buildArmor("sage", EBAdvancementTriggers.ARCANE_WORKBENCH.getId(), armorSet, EBItems.SAGE_ROBE.get(), Component.translatable("advancement.ebwizardry.sage"), Component.translatable("advancement.ebwizardry.sage.desc"), SAGE_ITEMS, consumer, existingFileHelper);
        Advancement restoreImbuementAltar = Advancement.Builder.advancement().parent(findLibraryRuins).display(EBBlocks.IMBUEMENT_ALTAR.get(),
                Component.translatable("advancement.ebwizardry.restore_imbuement_altar"), Component.translatable("advancement.ebwizardry.restore_imbuement_altar.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", new com.binaris.wizardry.content.advancement.WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.IMBUEMENT_ALTAR.getId())).save(consumer, WizardryMainMod.location("restore_imbuement_altar"), existingFileHelper);
        Advancement restoreRuinedBook = Advancement.Builder.advancement().parent(restoreImbuementAltar).display(EBItems.RUINED_SPELL_BOOK.get(), Component.translatable("advancement.ebwizardry.restore_ruined_book"), Component.translatable("advancement.ebwizardry.restore_ruined_book.desc"), null, FrameType.TASK, true, true, false).addCriterion("criterion", new com.binaris.wizardry.content.advancement.WizardryContainerTrigger.TriggerInstance(EBAdvancementTriggers.IMBUEMENT_ALTAR.getId(), ItemPredicate.Builder.item().of(EBItems.SPELL_BOOK.get()).build())).save(consumer, WizardryMainMod.location("restore_ruined_book"), existingFileHelper);
        Advancement maxOutWand = Advancement.Builder.advancement().parent(master).display(EBItems.APPRENTICE_ARCANE_TOME.get(), Component.translatable("advancement.ebwizardry.max_out_wand"), Component.translatable("advancement.ebwizardry.max_out_wand.desc"), null, FrameType.GOAL, true, true, false).addCriterion("criterion", new WizardryAdvancementTrigger.TriggerInstance(EBAdvancementTriggers.MAX_OUT_WAND.getId())).save(consumer, WizardryMainMod.location("max_out_wand"), existingFileHelper);
        Advancement discoverMaster = Advancement.Builder.advancement().parent(spellFailure).display(Items.BLAZE_POWDER, Component.translatable("advancement.ebwizardry.discover_master_spell"), Component.translatable("advancement.ebwizardry.discover_master_spell.desc"), null, FrameType.CHALLENGE, true, true, false).addCriterion("criterion", new com.binaris.wizardry.content.advancement.SpellDiscoveryTrigger.TriggerInstance(new com.binaris.wizardry.content.advancement.SpellPredicate(null, Set.of(SpellTiers.MASTER), Set.of()), EBDiscoverSpellEvent.Source.CASTING)).save(consumer, WizardryMainMod.location("discover_master_spell"), existingFileHelper);
        Advancement createElementalArmor = buildArmor("create_elemental_armor", EBAdvancementTriggers.IMBUEMENT_ALTAR.getId(), restoreImbuementAltar, EBItems.WIZARD_HAT_LIGHTNING.get(), Component.translatable("advancement.ebwizardry.create_elemental_armor"), Component.translatable("advancement.ebwizardry.create_elemental_armor.desc"), WIZARD_ITEMS, consumer, existingFileHelper);
        Advancement battlemage = buildArmor("battlemage", EBAdvancementTriggers.ARCANE_WORKBENCH.getId(), armorSet, EBItems.BATTLEMAGE_BOOTS.get(), Component.translatable("advancement.ebwizardry.battlemage"), Component.translatable("advancement.ebwizardry.battlemage.desc"), BATTLEMAGE_ITEMS, consumer, existingFileHelper);
    }
}
